<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopConfigTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('shop_config')->delete();

        DB::table('shop_config')->insert(array(

            array(
                'id' => 1,
                'parent_id' => 0,
                'code' => 'shop_info',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 2,
                'parent_id' => 0,
                'code' => 'basic',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 3,
                'parent_id' => 0,
                'code' => 'display',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 4,
                'parent_id' => 0,
                'code' => 'shopping_flow',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 5,
                'parent_id' => 0,
                'code' => 'smtp',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 6,
                'parent_id' => 0,
                'code' => 'hidden',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 7,
                'parent_id' => 0,
                'code' => 'goods',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 8,
                'parent_id' => 0,
                'code' => 'sms',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 9,
                'parent_id' => 0,
                'code' => 'wap',
                'type' => 'group',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 101,
                'parent_id' => 1,
                'code' => 'shop_name',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'ECTouch',
                'sort_order' => 1,
            ),

            array(
                'id' => 102,
                'parent_id' => 1,
                'code' => 'shop_title',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'ECTouch演示站',
                'sort_order' => 1,
            ),

            array(
                'id' => 103,
                'parent_id' => 1,
                'code' => 'shop_desc',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'ECTouch演示站',
                'sort_order' => 1,
            ),

            array(
                'id' => 104,
                'parent_id' => 1,
                'code' => 'shop_keywords',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'ECTouch演示站',
                'sort_order' => 1,
            ),

            array(
                'id' => 105,
                'parent_id' => 1,
                'code' => 'shop_country',
                'type' => 'manual',
                'store_range' => '',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 106,
                'parent_id' => 1,
                'code' => 'shop_province',
                'type' => 'manual',
                'store_range' => '',
                'store_dir' => '',
                'value' => '2',
                'sort_order' => 1,
            ),

            array(
                'id' => 107,
                'parent_id' => 1,
                'code' => 'shop_city',
                'type' => 'manual',
                'store_range' => '',
                'store_dir' => '',
                'value' => '52',
                'sort_order' => 1,
            ),

            array(
                'id' => 108,
                'parent_id' => 1,
                'code' => 'shop_address',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 109,
                'parent_id' => 1,
                'code' => 'qq',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 110,
                'parent_id' => 1,
                'code' => 'ww',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 111,
                'parent_id' => 1,
                'code' => 'skype',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 112,
                'parent_id' => 1,
                'code' => 'ym',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 113,
                'parent_id' => 1,
                'code' => 'msn',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 114,
                'parent_id' => 1,
                'code' => 'service_email',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 115,
                'parent_id' => 1,
                'code' => 'service_phone',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 116,
                'parent_id' => 1,
                'code' => 'shop_closed',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 117,
                'parent_id' => 1,
                'code' => 'close_comment',
                'type' => 'textarea',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 118,
                'parent_id' => 1,
                'code' => 'shop_logo',
                'type' => 'file',
                'store_range' => '',
                'store_dir' => '../themes/{$template}/images/',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 119,
                'parent_id' => 1,
                'code' => 'licensed',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 120,
                'parent_id' => 1,
                'code' => 'user_notice',
                'type' => 'textarea',
                'store_range' => '',
                'store_dir' => '',
                'value' => '用户中心公告！',
                'sort_order' => 1,
            ),

            array(
                'id' => 121,
                'parent_id' => 1,
                'code' => 'shop_notice',
                'type' => 'textarea',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 122,
                'parent_id' => 1,
                'code' => 'shop_reg_closed',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 201,
                'parent_id' => 2,
                'code' => 'lang',
                'type' => 'manual',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'zh_cn',
                'sort_order' => 1,
            ),

            array(
                'id' => 202,
                'parent_id' => 2,
                'code' => 'icp_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 203,
                'parent_id' => 2,
                'code' => 'icp_file',
                'type' => 'file',
                'store_range' => '',
                'store_dir' => '../cert/',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 204,
                'parent_id' => 2,
                'code' => 'watermark',
                'type' => 'file',
                'store_range' => '',
                'store_dir' => '../images/',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 205,
                'parent_id' => 2,
                'code' => 'watermark_place',
                'type' => 'select',
                'store_range' => '0,1,2,3,4,5',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 206,
                'parent_id' => 2,
                'code' => 'watermark_alpha',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '65',
                'sort_order' => 1,
            ),

            array(
                'id' => 207,
                'parent_id' => 2,
                'code' => 'use_storage',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 208,
                'parent_id' => 2,
                'code' => 'market_price_rate',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '1.2',
                'sort_order' => 1,
            ),

            array(
                'id' => 209,
                'parent_id' => 2,
                'code' => 'rewrite',
                'type' => 'select',
                'store_range' => '0,1,2',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 210,
                'parent_id' => 2,
                'code' => 'integral_name',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '积分',
                'sort_order' => 1,
            ),

            array(
                'id' => 211,
                'parent_id' => 2,
                'code' => 'integral_scale',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 212,
                'parent_id' => 2,
                'code' => 'integral_percent',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 213,
                'parent_id' => 2,
                'code' => 'sn_prefix',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'SN',
                'sort_order' => 1,
            ),

            array(
                'id' => 214,
                'parent_id' => 2,
                'code' => 'comment_check',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 215,
                'parent_id' => 2,
                'code' => 'no_picture',
                'type' => 'file',
                'store_range' => '',
                'store_dir' => '../images/',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 218,
                'parent_id' => 2,
                'code' => 'stats_code',
                'type' => 'textarea',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 219,
                'parent_id' => 2,
                'code' => 'cache_time',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '3600',
                'sort_order' => 1,
            ),

            array(
                'id' => 220,
                'parent_id' => 2,
                'code' => 'register_points',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 221,
                'parent_id' => 2,
                'code' => 'enable_gzip',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 222,
                'parent_id' => 2,
                'code' => 'top10_time',
                'type' => 'select',
                'store_range' => '0,1,2,3,4',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 223,
                'parent_id' => 2,
                'code' => 'timezone',
                'type' => 'options',
                'store_range' => '-12,-11,-10,-9,-8,-7,-6,-5,-4,-3.5,-3,-2,-1,0,1,2,3,3.5,4,4.5,5,5.5,5.75,6,6.5,7,8,9,9.5,10,11,12',
                'store_dir' => '',
                'value' => '8',
                'sort_order' => 1,
            ),

            array(
                'id' => 224,
                'parent_id' => 2,
                'code' => 'upload_size_limit',
                'type' => 'options',
                'store_range' => '-1,0,64,128,256,512,1024,2048,4096',
                'store_dir' => '',
                'value' => '64',
                'sort_order' => 1,
            ),

            array(
                'id' => 226,
                'parent_id' => 2,
                'code' => 'cron_method',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 227,
                'parent_id' => 2,
                'code' => 'comment_factor',
                'type' => 'select',
                'store_range' => '0,1,2,3',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 228,
                'parent_id' => 2,
                'code' => 'enable_order_check',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 229,
                'parent_id' => 2,
                'code' => 'default_storage',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 230,
                'parent_id' => 2,
                'code' => 'bgcolor',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '#FFFFFF',
                'sort_order' => 1,
            ),

            array(
                'id' => 231,
                'parent_id' => 2,
                'code' => 'visit_stats',
                'type' => 'select',
                'store_range' => 'on,off',
                'store_dir' => '',
                'value' => 'on',
                'sort_order' => 1,
            ),

            array(
                'id' => 232,
                'parent_id' => 2,
                'code' => 'send_mail_on',
                'type' => 'select',
                'store_range' => 'on,off',
                'store_dir' => '',
                'value' => 'off',
                'sort_order' => 1,
            ),

            array(
                'id' => 233,
                'parent_id' => 2,
                'code' => 'auto_generate_gallery',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 234,
                'parent_id' => 2,
                'code' => 'retain_original_img',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 235,
                'parent_id' => 2,
                'code' => 'member_email_validate',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 236,
                'parent_id' => 2,
                'code' => 'message_board',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 239,
                'parent_id' => 2,
                'code' => 'certificate_id',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 240,
                'parent_id' => 2,
                'code' => 'token',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 241,
                'parent_id' => 2,
                'code' => 'certi',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'http://service.shopex.cn/openapi/api.php',
                'sort_order' => 1,
            ),

            array(
                'id' => 242,
                'parent_id' => 2,
                'code' => 'send_verify_email',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 243,
                'parent_id' => 2,
                'code' => 'ent_id',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 244,
                'parent_id' => 2,
                'code' => 'ent_ac',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 245,
                'parent_id' => 2,
                'code' => 'ent_sign',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 246,
                'parent_id' => 2,
                'code' => 'ent_email',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 301,
                'parent_id' => 3,
                'code' => 'date_format',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'Y-m-d',
                'sort_order' => 1,
            ),

            array(
                'id' => 302,
                'parent_id' => 3,
                'code' => 'time_format',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'Y-m-d H:i:s',
                'sort_order' => 1,
            ),

            array(
                'id' => 303,
                'parent_id' => 3,
                'code' => 'currency_format',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '￥%s元',
                'sort_order' => 1,
            ),

            array(
                'id' => 304,
                'parent_id' => 3,
                'code' => 'thumb_width',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '100',
                'sort_order' => 1,
            ),

            array(
                'id' => 305,
                'parent_id' => 3,
                'code' => 'thumb_height',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '100',
                'sort_order' => 1,
            ),

            array(
                'id' => 306,
                'parent_id' => 3,
                'code' => 'image_width',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '230',
                'sort_order' => 1,
            ),

            array(
                'id' => 307,
                'parent_id' => 3,
                'code' => 'image_height',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '230',
                'sort_order' => 1,
            ),

            array(
                'id' => 312,
                'parent_id' => 3,
                'code' => 'top_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '10',
                'sort_order' => 1,
            ),

            array(
                'id' => 313,
                'parent_id' => 3,
                'code' => 'history_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '5',
                'sort_order' => 1,
            ),

            array(
                'id' => 314,
                'parent_id' => 3,
                'code' => 'comments_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '5',
                'sort_order' => 1,
            ),

            array(
                'id' => 315,
                'parent_id' => 3,
                'code' => 'bought_goods',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '3',
                'sort_order' => 1,
            ),

            array(
                'id' => 316,
                'parent_id' => 3,
                'code' => 'article_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '8',
                'sort_order' => 1,
            ),

            array(
                'id' => 317,
                'parent_id' => 3,
                'code' => 'goods_name_length',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '7',
                'sort_order' => 1,
            ),

            array(
                'id' => 318,
                'parent_id' => 3,
                'code' => 'price_format',
                'type' => 'select',
                'store_range' => '0,1,2,3,4,5',
                'store_dir' => '',
                'value' => '5',
                'sort_order' => 1,
            ),

            array(
                'id' => 319,
                'parent_id' => 3,
                'code' => 'page_size',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '10',
                'sort_order' => 1,
            ),

            array(
                'id' => 320,
                'parent_id' => 3,
                'code' => 'sort_order_type',
                'type' => 'select',
                'store_range' => '0,1,2',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 321,
                'parent_id' => 3,
                'code' => 'sort_order_method',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 322,
                'parent_id' => 3,
                'code' => 'show_order_type',
                'type' => 'select',
                'store_range' => '0,1,2',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 323,
                'parent_id' => 3,
                'code' => 'attr_related_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '5',
                'sort_order' => 1,
            ),

            array(
                'id' => 324,
                'parent_id' => 3,
                'code' => 'goods_gallery_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '5',
                'sort_order' => 1,
            ),

            array(
                'id' => 325,
                'parent_id' => 3,
                'code' => 'article_title_length',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '16',
                'sort_order' => 1,
            ),

            array(
                'id' => 326,
                'parent_id' => 3,
                'code' => 'name_of_region_1',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '国家',
                'sort_order' => 1,
            ),

            array(
                'id' => 327,
                'parent_id' => 3,
                'code' => 'name_of_region_2',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '省',
                'sort_order' => 1,
            ),

            array(
                'id' => 328,
                'parent_id' => 3,
                'code' => 'name_of_region_3',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '市',
                'sort_order' => 1,
            ),

            array(
                'id' => 329,
                'parent_id' => 3,
                'code' => 'name_of_region_4',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '区',
                'sort_order' => 1,
            ),

            array(
                'id' => 330,
                'parent_id' => 3,
                'code' => 'search_keywords',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 0,
            ),

            array(
                'id' => 332,
                'parent_id' => 3,
                'code' => 'related_goods_number',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '4',
                'sort_order' => 1,
            ),

            array(
                'id' => 333,
                'parent_id' => 3,
                'code' => 'help_open',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 334,
                'parent_id' => 3,
                'code' => 'article_page_size',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '10',
                'sort_order' => 1,
            ),

            array(
                'id' => 335,
                'parent_id' => 3,
                'code' => 'page_style',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 336,
                'parent_id' => 3,
                'code' => 'recommend_order',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 337,
                'parent_id' => 3,
                'code' => 'index_ad',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'sys',
                'sort_order' => 1,
            ),

            array(
                'id' => 401,
                'parent_id' => 4,
                'code' => 'can_invoice',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 402,
                'parent_id' => 4,
                'code' => 'use_integral',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 403,
                'parent_id' => 4,
                'code' => 'use_bonus',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 404,
                'parent_id' => 4,
                'code' => 'use_surplus',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 405,
                'parent_id' => 4,
                'code' => 'use_how_oos',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 406,
                'parent_id' => 4,
                'code' => 'send_confirm_email',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 407,
                'parent_id' => 4,
                'code' => 'send_ship_email',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 408,
                'parent_id' => 4,
                'code' => 'send_cancel_email',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 409,
                'parent_id' => 4,
                'code' => 'send_invalid_email',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 410,
                'parent_id' => 4,
                'code' => 'order_pay_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 411,
                'parent_id' => 4,
                'code' => 'order_unpay_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 412,
                'parent_id' => 4,
                'code' => 'order_ship_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 413,
                'parent_id' => 4,
                'code' => 'order_receive_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 414,
                'parent_id' => 4,
                'code' => 'order_unship_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 415,
                'parent_id' => 4,
                'code' => 'order_return_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 416,
                'parent_id' => 4,
                'code' => 'order_invalid_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 417,
                'parent_id' => 4,
                'code' => 'order_cancel_note',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 418,
                'parent_id' => 4,
                'code' => 'invoice_content',
                'type' => 'textarea',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 419,
                'parent_id' => 4,
                'code' => 'anonymous_buy',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 420,
                'parent_id' => 4,
                'code' => 'min_goods_amount',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 421,
                'parent_id' => 4,
                'code' => 'one_step_buy',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 422,
                'parent_id' => 4,
                'code' => 'invoice_type',
                'type' => 'manual',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'a:2:{s:4:"type";a:3:{i:0;s:1:"1";i:1;s:1:"2";i:2;s:0:"";}s:4:"rate";a:3:{i:0;d:1;i:1;d:1.5;i:2;d:0;}}',
                'sort_order' => 1,
            ),

            array(
                'id' => 423,
                'parent_id' => 4,
                'code' => 'stock_dec_time',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 424,
                'parent_id' => 4,
                'code' => 'cart_confirm',
                'type' => 'options',
                'store_range' => '1,2,3,4',
                'store_dir' => '',
                'value' => '3',
                'sort_order' => 0,
            ),

            array(
                'id' => 425,
                'parent_id' => 4,
                'code' => 'send_service_email',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 426,
                'parent_id' => 4,
                'code' => 'show_goods_in_cart',
                'type' => 'select',
                'store_range' => '1,2,3',
                'store_dir' => '',
                'value' => '3',
                'sort_order' => 1,
            ),

            array(
                'id' => 427,
                'parent_id' => 4,
                'code' => 'show_attr_in_cart',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 501,
                'parent_id' => 5,
                'code' => 'smtp_host',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'localhost',
                'sort_order' => 1,
            ),

            array(
                'id' => 502,
                'parent_id' => 5,
                'code' => 'smtp_port',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '25',
                'sort_order' => 1,
            ),

            array(
                'id' => 503,
                'parent_id' => 5,
                'code' => 'smtp_user',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 504,
                'parent_id' => 5,
                'code' => 'smtp_pass',
                'type' => 'password',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 505,
                'parent_id' => 5,
                'code' => 'smtp_mail',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 506,
                'parent_id' => 5,
                'code' => 'mail_charset',
                'type' => 'select',
                'store_range' => 'UTF8,GB2312,BIG5',
                'store_dir' => '',
                'value' => 'UTF8',
                'sort_order' => 1,
            ),

            array(
                'id' => 507,
                'parent_id' => 5,
                'code' => 'mail_service',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 0,
            ),

            array(
                'id' => 508,
                'parent_id' => 5,
                'code' => 'smtp_ssl',
                'type' => 'select',
                'store_range' => '0,1',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 0,
            ),

            array(
                'id' => 601,
                'parent_id' => 6,
                'code' => 'integrate_code',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'ectouch',
                'sort_order' => 1,
            ),

            array(
                'id' => 602,
                'parent_id' => 6,
                'code' => 'integrate_config',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 603,
                'parent_id' => 6,
                'code' => 'hash_code',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '4c5fe100345afa94721aa389ac2b835c',
                'sort_order' => 1,
            ),

            array(
                'id' => 604,
                'parent_id' => 6,
                'code' => 'template',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'default',
                'sort_order' => 1,
            ),

            array(
                'id' => 605,
                'parent_id' => 6,
                'code' => 'install_date',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '1542102810',
                'sort_order' => 1,
            ),

            array(
                'id' => 606,
                'parent_id' => 6,
                'code' => 'version',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'v1.0.0',
                'sort_order' => 1,
            ),

            array(
                'id' => 607,
                'parent_id' => 6,
                'code' => 'sms_user_name',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 608,
                'parent_id' => 6,
                'code' => 'sms_password',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 609,
                'parent_id' => 6,
                'code' => 'sms_auth_str',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 610,
                'parent_id' => 6,
                'code' => 'sms_domain',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 611,
                'parent_id' => 6,
                'code' => 'sms_count',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 612,
                'parent_id' => 6,
                'code' => 'sms_total_money',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 613,
                'parent_id' => 6,
                'code' => 'sms_balance',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 614,
                'parent_id' => 6,
                'code' => 'sms_last_request',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 616,
                'parent_id' => 6,
                'code' => 'affiliate',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'a:3:{s:6:"config";a:7:{s:6:"expire";d:24;s:11:"expire_unit";s:4:"hour";s:11:"separate_by";i:0;s:15:"level_point_all";s:2:"5%";s:15:"level_money_all";s:2:"1%";s:18:"level_register_all";i:2;s:17:"level_register_up";i:60;}s:4:"item";a:4:{i:0;a:2:{s:11:"level_point";s:3:"60%";s:11:"level_money";s:3:"60%";}i:1;a:2:{s:11:"level_point";s:3:"30%";s:11:"level_money";s:3:"30%";}i:2;a:2:{s:11:"level_point";s:2:"7%";s:11:"level_money";s:2:"7%";}i:3;a:2:{s:11:"level_point";s:2:"3%";s:11:"level_money";s:2:"3%";}}s:2:"on";i:1;}',
                'sort_order' => 1,
            ),

            array(
                'id' => 617,
                'parent_id' => 6,
                'code' => 'captcha',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '12',
                'sort_order' => 1,
            ),

            array(
                'id' => 618,
                'parent_id' => 6,
                'code' => 'captcha_width',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '100',
                'sort_order' => 1,
            ),

            array(
                'id' => 619,
                'parent_id' => 6,
                'code' => 'captcha_height',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '20',
                'sort_order' => 1,
            ),

            array(
                'id' => 620,
                'parent_id' => 6,
                'code' => 'sitemap',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'a:6:{s:19:"homepage_changefreq";s:6:"hourly";s:17:"homepage_priority";s:3:"0.9";s:19:"category_changefreq";s:6:"hourly";s:17:"category_priority";s:3:"0.8";s:18:"content_changefreq";s:6:"weekly";s:16:"content_priority";s:3:"0.7";}',
                'sort_order' => 0,
            ),

            array(
                'id' => 621,
                'parent_id' => 6,
                'code' => 'points_rule',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 0,
            ),

            array(
                'id' => 622,
                'parent_id' => 6,
                'code' => 'flash_theme',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => 'dynfocus',
                'sort_order' => 1,
            ),

            array(
                'id' => 623,
                'parent_id' => 6,
                'code' => 'stylename',
                'type' => 'hidden',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 701,
                'parent_id' => 7,
                'code' => 'show_goodssn',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 702,
                'parent_id' => 7,
                'code' => 'show_brand',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 703,
                'parent_id' => 7,
                'code' => 'show_goodsweight',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 704,
                'parent_id' => 7,
                'code' => 'show_goodsnumber',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 705,
                'parent_id' => 7,
                'code' => 'show_addtime',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 706,
                'parent_id' => 7,
                'code' => 'goodsattr_style',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 707,
                'parent_id' => 7,
                'code' => 'show_marketprice',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),

            array(
                'id' => 801,
                'parent_id' => 8,
                'code' => 'sms_shop_mobile',
                'type' => 'text',
                'store_range' => '',
                'store_dir' => '',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 802,
                'parent_id' => 8,
                'code' => 'sms_order_placed',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 803,
                'parent_id' => 8,
                'code' => 'sms_order_payed',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 804,
                'parent_id' => 8,
                'code' => 'sms_order_shipped',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 901,
                'parent_id' => 9,
                'code' => 'wap_config',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '0',
                'sort_order' => 1,
            ),

            array(
                'id' => 902,
                'parent_id' => 9,
                'code' => 'wap_logo',
                'type' => 'file',
                'store_range' => '',
                'store_dir' => '../images/',
                'value' => '',
                'sort_order' => 1,
            ),

            array(
                'id' => 903,
                'parent_id' => 2,
                'code' => 'message_check',
                'type' => 'select',
                'store_range' => '1,0',
                'store_dir' => '',
                'value' => '1',
                'sort_order' => 1,
            ),
        ));
    }
}
