<?php

/**
 * 设置自定义后台入口路由
 */

defined('ADMIN_PATH') or define('ADMIN_PATH', 'admin');

Route::group(ADMIN_PATH, function () {
    Route::any('/', function () {
        return redirect(ADMIN_PATH . '/index.php');
    });
    Route::any('index.php', 'console/Index/index');
    Route::any('account_log.php', 'console/AccountLog/index');
    Route::any('ad_position.php', 'console/AdPosition/index');
    Route::any('admin_logs.php', 'console/AdminLogs/index');
    Route::any('ads.php', 'console/Ads/index');
    Route::any('adsense.php', 'console/Adsense/index');
    Route::any('affiliate_ck.php', 'console/AffiliateCk/index');
    Route::any('affiliate.php', 'console/Affiliate/index');
    Route::any('agency.php', 'console/Agency/index');
    Route::any('area_manage.php', 'console/AreaManage/index');
    Route::any('article_auto.php', 'console/ArticleAuto/index');
    Route::any('article.php', 'console/Article/index');
    Route::any('articlecat.php', 'console/Articlecat/index');
    Route::any('attention_list.php', 'console/AttentionList/index');
    Route::any('attribute.php', 'console/Attribute/index');
    Route::any('auction.php', 'console/Auction/index');
    Route::any('bonus.php', 'console/Bonus/index');
    Route::any('brand.php', 'console/Brand/index');
    Route::any('captcha.php', 'console/Captcha/index');
    Route::any('captcha_manage.php', 'console/CaptchaManage/index');
    Route::any('card.php', 'console/Card/index');
    Route::any('category.php', 'console/Category/index');
    Route::any('check_file_priv.php', 'console/CheckFilePriv/index');
    Route::any('cloud.php', 'console/Cloud/index');
    Route::any('comment_manage.php', 'console/CommentManage/index');
    Route::any('convert.php', 'console/Convert/index');
    Route::any('cron.php', 'console/Cron/index');
    Route::any('database.php', 'console/Database/index');
    Route::any('edit_languages.php', 'console/EditLanguages/index');
    Route::any('email_list.php', 'console/EmailList/index');
    Route::any('exchange_goods.php', 'console/ExchangeGoods/index');
    Route::any('favourable.php', 'console/Favourable/index');
    Route::any('filecheck.php', 'console/Filecheck/index');
    Route::any('flashplay.php', 'console/Flashplay/index');
    Route::any('flow_stats.php', 'console/FlowStats/index');
    Route::any('friend_link.php', 'console/FriendLink/index');
    Route::any('gen_goods_script.php', 'console/GenGoodsScript/index');
    Route::any('get_password.php', 'console/GetPassword/index');
    Route::any('goods_auto.php', 'console/GoodsAuto/index');
    Route::any('goods_batch.php', 'console/GoodsBatch/index');
    Route::any('goods_booking.php', 'console/GoodsBooking/index');
    Route::any('goods.php', 'console/Goods/index');
    Route::any('goods_export.php', 'console/GoodsExport/index');
    Route::any('goods_type.php', 'console/GoodsType/index');
    Route::any('group_buy.php', 'console/GroupBuy/index');
    Route::any('guest_stats.php', 'console/GuestStats/index');
    Route::any('help.php', 'console/Help/index');
    Route::any('integrate.php', 'console/Integrate/index');
    Route::any('license.php', 'console/License/index');
    Route::any('magazine_list.php', 'console/MagazineList/index');
    Route::any('mail_template.php', 'console/MailTemplate/index');
    Route::any('message.php', 'console/Message/index');
    Route::any('navigator.php', 'console/Navigator/index');
    Route::any('order.php', 'console/Order/index');
    Route::any('order_stats.php', 'console/OrderStats/index');
    Route::any('pack.php', 'console/Pack/index');
    Route::any('package.php', 'console/Package/index');
    Route::any('patch_num.php', 'console/PatchNum/index');
    Route::any('payment.php', 'console/Payment/index');
    Route::any('picture_batch.php', 'console/PictureBatch/index');
    Route::any('privilege.php', 'console/Privilege/index');
    Route::any('receive.php', 'console/Receive/index');
    Route::any('reg_fields.php', 'console/RegFields/index');
    Route::any('role.php', 'console/Role/index');
    Route::any('sale_general.php', 'console/SaleGeneral/index');
    Route::any('sale_list.php', 'console/SaleList/index');
    Route::any('sale_order.php', 'console/SaleOrder/index');
    Route::any('search_log.php', 'console/SearchLog/index');
    Route::any('searchengine_stats.php', 'console/SearchengineStats/index');
    Route::any('send.php', 'console/Send/index');
    Route::any('shipping_area.php', 'console/ShippingArea/index');
    Route::any('shipping.php', 'console/Shipping/index');
    Route::any('shop_config.php', 'console/ShopConfig/index');
    Route::any('shophelp.php', 'console/Shophelp/index');
    Route::any('shopinfo.php', 'console/Shopinfo/index');
    Route::any('sitemap.php', 'console/Sitemap/index');
    Route::any('sms.php', 'console/Sms/index');
    Route::any('snatch.php', 'console/Snatch/index');
    Route::any('sql.php', 'console/Sql/index');
    Route::any('suppliers.php', 'console/Suppliers/index');
    Route::any('suppliers_goods.php', 'console/SuppliersGoods/index');
    Route::any('tag_manage.php', 'console/TagManage/index');
    Route::any('template.php', 'console/Template/index');
    Route::any('topic.php', 'console/Topic/index');
    Route::any('user_account.php', 'console/UserAccount/index');
    Route::any('user_account_manage.php', 'console/UserAccountManage/index');
    Route::any('user_msg.php', 'console/UserMsg/index');
    Route::any('user_rank.php', 'console/UserRank/index');
    Route::any('users.php', 'console/Users/index');
    Route::any('users_order.php', 'console/UsersOrder/index');
    Route::any('view_sendlist.php', 'console/ViewSendlist/index');
    Route::any('virtual_card.php', 'console/VirtualCard/index');
    Route::any('visit_sold.php', 'console/VisitSold/index');
    Route::any('vote.php', 'console/Vote/index');
    Route::any('wholesale.php', 'console/Wholesale/index');
});
